# Generated by Django 4.2.1 on 2023-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='наименование')),
                ('category_description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='наименование')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение(превью)')),
                ('product_category', models.CharField(max_length=150, verbose_name='категория')),
                ('product_price', models.IntegerField(verbose_name='цена за покупку')),
                ('product_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('product_last_changes_date', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('product_name',),
            },
        ),
    ]
