# Generated by Django 4.2.1 on 2023-06-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='records/', verbose_name='изображение(превью)')),
                ('created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('sign_of_publication', models.BooleanField(default=True, verbose_name='активный')),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'get_latest_by': 'created',
            },
        ),
    ]
