# Generated by Django 4.2.1 on 2023-06-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_category_alter_product_price_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.IntegerField(verbose_name='номер версии'),
        ),
    ]
